// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa3jZb9YAqXT8hGdA4_01CjIhPmTSs4kk',
    appId: '1:755699099286:web:ae54ffff33d7e3147a44b7',
    messagingSenderId: '755699099286',
    projectId: 'oofy-app',
    authDomain: 'oofy-app.firebaseapp.com',
    storageBucket: 'oofy-app.firebasestorage.app',
    measurementId: 'G-VYTG9DG4RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhTgepgv6iKp-NigExI3W910s8rVpJxqM',
    appId: '1:755699099286:android:8f8880dc4d883a5a7a44b7',
    messagingSenderId: '755699099286',
    projectId: 'oofy-app',
    storageBucket: 'oofy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOu0c4x9EY1rAEO-fHRZZqVi-cf0qzgjc',
    appId: '1:755699099286:ios:d11f0c311446de547a44b7',
    messagingSenderId: '755699099286',
    projectId: 'oofy-app',
    storageBucket: 'oofy-app.firebasestorage.app',
    iosBundleId: 'dev.oobyruby.oofyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOu0c4x9EY1rAEO-fHRZZqVi-cf0qzgjc',
    appId: '1:755699099286:ios:d11f0c311446de547a44b7',
    messagingSenderId: '755699099286',
    projectId: 'oofy-app',
    storageBucket: 'oofy-app.firebasestorage.app',
    iosBundleId: 'dev.oobyruby.oofyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa3jZb9YAqXT8hGdA4_01CjIhPmTSs4kk',
    appId: '1:755699099286:web:9e1e8525cbb62ee67a44b7',
    messagingSenderId: '755699099286',
    projectId: 'oofy-app',
    authDomain: 'oofy-app.firebaseapp.com',
    storageBucket: 'oofy-app.firebasestorage.app',
    measurementId: 'G-6GXWHQ62T3',
  );
}
